feat(BUILD-1436): sbom plugin
SonarSource/sonar-scanner-cli pull request #130
Opened 2022-04-11 09:56 UTC by julien-carsique-sonarsource

WIP

Add SBOM plugin

2022-04-12 11:45 UTC, tomverin approved these changes

2022-04-13 06:55 UTC, tomverin requested changes

2022-04-13 06:55 UTC, tomverin commented on pom.xml
> +    <version>61.0.139</version>
61.0.147

2022-04-13 18:25 UTC, dbmeneses approved these changes

2022-04-13 20:52 UTC, merged