SQSCANNER-68 - Automatically trigger docker release on new CLI release
SonarSource/sonar-scanner-cli pull request #93
Opened 2020-09-30 09:46 UTC by mark-rekveld-sonarsource

New release action

2020-09-30 09:47 UTC, mark-rekveld-sonarsource commented
As discussed this action should only be missing the release trigger to the sonar-scanner-cli-docker repo

2020-09-30 13:22 UTC, mark-rekveld-sonarsource commented
@malena-ebert-sonarsource I added the trigger to the docker repo in df41e30

2020-10-02 10:01 UTC, malena-ebert-sonarsource requested changes

2020-10-02 10:01 UTC, malena-ebert-sonarsource commented on .github/workflows/release.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> The token's permissions are limited to the repository that contains your workflow.

You should be able to use `secrets.RELEASE_GITHUB_TOKEN` for this use case.

2020-10-02 10:51 UTC, mark-rekveld-sonarsource commented on .github/workflows/release.yml
> +        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Addressed in 912e42f

2020-10-02 12:06 UTC, malena-ebert-sonarsource approved these changes
LGFM

2020-10-02 12:42 UTC, merged